name: farmers_app
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  searchable_dropdown:
  shared_preferences: ^2.0.5
  flutter_statusbarcolor: ^0.2.3
  intl_phone_field: ^1.4.2
  cloud_firestore: ^1.0.1
  firebase_core: ^1.0.1
  firebase_auth: ^1.0.1
  firebase_messaging:
  toast:
  http:
  charts_flutter:
  async:
  grouped_list: ^4.0.0
  awesome_dialog:
  flutter_launcher_icons:
  flutter_boom_menu: ^1.0.2
  provider:
  firebase_storage:
  image_picker:





dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/401.png
    - assets/nodata.png
    - assets/others.png
    - assets/female.png
    - assets/male.png
    - assets/icons/


flutter_icons:
  image_path: "assets/icon2.png"
  image_path_ios: "assets/icon2.png"
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "assets/icon2.png"
  adaptive_icon_foreground: "assets/icon2.png"
#
#flutter_icons:
#  ios: true
#  android: true
#  image_path_ios: "assets/ROMPIN.png"
#  image_path_android: "assets/ROMPIN.png"
#  adaptive_icon_background: "assets/background.png"
#  adaptive_icon_foreground: "assets/foreground.png"
  #  run flutter packages pub run flutter_launcher_icons:main